### ISSUE TITLE
Server does not work with current version of plugin

### ISSUE THREAD

**Issue by tylanphear** [davidvorona/gimp-server#2]
Trying to run the server at the latest commit, using the instructions in the README, I get the following error:

```
Error: No room ID defined for this socket
    at Socket.<anonymous> (/home/tyg13/gimp-server/server.js:81:27)
    at Socket.emit (node:events:390:28)
    at Socket.emitUntyped (/home/tyg13/gimp-server/node_modules/socket.io/dist/typed-events.js:69:22)
    at /home/tyg13/gimp-server/node_modules/socket.io/dist/socket.js:428:39
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

Looking in the code, it looks like the `roomId` is not getting set because the server never receives the `connection-ack` event. I can see in the client code that it should be sending this event -- and I am able to see the clients connect:

```
Listening on *:3000
Client connected: iUDnawgUwAqeb8exAAAC
Client connected: 1XXgRdGtXbpDE3QOAAAD
Client connected: 8YHHuXtfr0M-N4poAAAF
Client connected: Res7cSH-1HviqxZRAAAH
Client connected: zVBFqnLZKatQteP_AAAJ
Client connected: bxuZr23SPPiMyVV3AAAL
Client connected: YaeX2m1O1h_cD8ucAAAN
```

But immediately after the clients connect (side note: looks like multiple connections per client -- we've only got 2 online at the moment), I get the above error.

Just wanted to add: I think this is a great idea, and thank you for the work you've done so far to see it through.

**Comment by davidvorona** [comment]
Hey--I'm about a day away from submitting v2 to the plugin hub. I was lazy and didn't think anyone would take the time to set this up so I didn't bother leaving [instructions](https://github.com/davidvorona/gim-plugin/issues/13#issuecomment-1009180751) until someone added an issue in the plugin repo (basically, pin your server to this commit: https://github.com/davidvorona/gimp-server/tree/8bba493c21ce867bbaced5bf0c972a7506457902).

You're right by the way, what you downloaded on the hub is meant to communicate with a server that supports 1 group. When the next version comes out, it'll include better map tracking, a side panel with real-time data, and a default public server that everyone can connect to (one that supports multiple groups).

Hope this helps. Sorry about the confusion.

**Comment by tylanphear** [comment]
Ah, that makes sense. I figured as much, just wanted to check to see that I wasn't doing anything stupid (and also to figure out how to make it work in the meantime). Thanks for the quick response!

**Comment by davidvorona** [comment]
Fixed in v2, out now
